google_service_account = {
  type = "service_account",
  project_id = "earnings-transcript-analyzer",
  private_key_id = "74cae76572956ea0b6f40865005225ed8bce4082",
  private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuTykW54PvUI18
5OgpHr79Js2I1cb+sWlw6DPH6M0F1PQAacLCBSpz0h+jzGg612Qu+JLomU6eaZsg
2qoouY9ZWYoR1BY3JwnvaL5GRueSwhdnS8nbAMKI0TJHSld+Rv5csi6RNOUh83/X
x7pGCTAFAxicToCM2EbfdZkAXjswsaVC3FziR00yIKz9tJTUsaWJE58cRajjo4Oy
uol9oqHI1hRdLMEdRRjEbYlrviAjp0Dl0JLKnnT3PvqnUlgbjZMbopxhk4f2/217
vfsT0qe4BaHRcLZ1u3lCOBnPOe79upwL0vF/D457nIXd2JLEpeN9FswnY5xFXG6B
M5M/0bAXAgMBAAECggEACXzUjeMZxXply8utLqPLndLcCBvUDNk86yuFugFcEM+y
XPK6FOkcEkQjJb1tWkU5YOx1w+79nlYS3rBtkkbmBw/TxJGoiJBO6aGSuGzek5iN
6+OY//B5e4ygxyGZmTglsIegTOtgohRIu/F/8ZT0G1RmUAez1owPxipL+Cmo4McL
lTSeOl1/NIzSqcSGQJeNP2t0VrEtncZL9aYLbKHSC1/c6UPWetjae6tXmHwPYpbm
IqKMYJOWwGZVhWhJcKqJG7p2dWlvRsDXEWVb2RoxaNQa7kvTh4tK7Wa05cmuYFVg
EdVFbkJBVcMUO59mUn4HkfnmxdSrUTLdZqqXwbdceQKBgQDUEXdWqd2YXgWN/lWI
ac2F4DORlP1V91zzPpHMYQB1rSTolFxfQpzi9Fhv1z06nFP0RngAC4e5p8vbFULb
aR/j/D6RzA+/x/+XaxJf81oMs1zYsWC17B/Ze5Z+7zGsFSxLtoJEBbcvkVaKfQTg
GVNTzRW3b2LK+tYRvcZKmik53wKBgQDSazw69RSilbEVgYpq3V8R2MnGZe8oKn2g
qiyoG5NHvGTaCMBTNm7xAwlfA4mmPpgtngRhGX30ePXBIjEPeRn2MxLKCjOO8u9k
CVfyEt5bPa0Srh24ywwI+30vt6ufwpkGmmCH5wyv6dM0g1xR2mlRhq5jmLGQ0bTP
vd2RD3TAyQKBgACckEiKst3mn4N6UUrUa0hQjjWERXrC/NyiuI7rVLICLtIQ43dO
3N72r26bI00Q+FkC/wOZBOovJrJaDFhPpEznBFMtUHpQHFeWcnYeYIsa1VC2qj28
EZdx+Mwi6nTBluAdBaEmlxGnDKXXmHUA/bGHLOHbi2BkesuQTYsXiLjnAoGAReS6
3/aSgSLp7HPYD4Ey2BHDjDRFyXi7vAdqx/hI5rYsZcQsZjeZiFLy5O2e5mq6T8TC
PaKjFPas4xdBZptaRU5XumbDE4OcgwUbglxEIdiNybuuQbioab9nqNcAmhOgkvHq
iJn1u+UWc8YCf2nmO99Zw9lveeQ+hBbUJyAULwkCgYEArVxbsK+aT3dkbaFKucOT
fCNpmEYn/5sL70PdDNlIsImYpeNwXKfYsdPs43sBOW2tcPdD6A6RfZCNLcP1xD1u
FMzvcWhIvg61yH4J3/zwfXVHF466h/06Lr6UwBYH5fOn/RRveYUVH2SKpiWbwzgG
dBCTR747gxaoRoeIqE+9Vaw=
-----END PRIVATE KEY-----
""",
  client_email = "streamlit-signups@earnings-transcript-analyzer.iam.gserviceaccount.com",
  client_id = "107177932080872956470",
  auth_uri = "https://accounts.google.com/o/oauth2/auth",
  token_uri = "https://oauth2.googleapis.com/token",
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs",
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-signups%40earnings-transcript-analyzer.iam.gserviceaccount.com",
  universe_domain = "googleapis.com"
}

google_sheet_id = "1Qz3-iM9UllqSC1Pi7BspihnENIkrOgTBhlKYZq4bZXY"
